### ISSUE TITLE
Missing convert

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/mediawiki-sandstorm#1]
I uploaded an image, and the template it goes in is resized a bit. Instead of the image showing in my template, I see this:

`Error creating thumbnail: /bin/bash: /usr/bin/convert: No such file or directory Error code: 127`

**Comment by zenhack** [comment]
Ok, I probably just need to make sure imagemagick gets included.

**Comment by zenhack** [comment]
(I actually put this in alwaysInclude, but I bet there's a shared library it depends on that's not getting pulled in, so I'll probably have to actually exercise the functionality to get it into sandstorm-files.list)

**Comment by ocdtrekkie** [comment]
If you upload a full 1080p picture to a grain, it will thumbnail it, triggering this functionality.
