### ISSUE TITLE
Fatal exception of type DBQueryError

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/mediawiki-sandstorm#4]
Sometimes when I try to submit a new page, I am getting this error:

`[730746f7a26a9eeb0055f952] 2022-05-15 18:23:25: Fatal exception of type "Wikimedia\Rdbms\DBQueryError"`

What's strange is: The actual database operation succeeds. When I reload the grain or refresh the page, the data is updated.

**Comment by ocdtrekkie** [comment]
I just got it on a page load too, though with some advice this time:

`Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to show detailed debugging information`

It's intermittent enough it will probably be annoying to sort out.

**Comment by zenhack** [comment]
I don't think I've seen that. If you can reproduce it semi-reliably, patching LocalSettings.php as instructed (it's even there commented out) and testing would be useful.

**Comment by ocdtrekkie** [comment]
Is there any reason we shouldn't just set that setting in the main package? I doubt it will leak data not visible to people with access to the grain.

**Comment by zenhack** [comment]
I don't see a problem with it. Probably a good idea then.

**Comment by zenhack** [comment]
The new spk I just pushed changes that setting.

**Comment by ocdtrekkie** [comment]
You might've fixed this via the other changes. I did quite a few more operations than had triggered this error message before and I haven't seen it yet with the new package. I have a bit more to do to finish archiving this wiki, and if I don't see this issue again by the time I finish it, I will assume it's fixed and close this issue.
